# Setup
title:               Lanyon
tagline:             'A Jekyll theme'
description:         ''
url:                 https://tom5610.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Tom Liu
  url:               https://tom5610.github.io
  email:

# Gems
plugins:
  - jekyll-paginate

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom vars
version:             1.0.0
